<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="page-title">
    <h1><?php echo Mage::helper('supportcontacts')->__('Contact Us') ?></h1>
</div>
<div class="contact-block">
	<div class="contact-left"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('contact_block')->toHtml() ?></div>
        <form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post" enctype="multipart/form-data">
            <div class="fieldset">
                <h2 class="legend"><?php echo Mage::helper('supportcontacts')->__('Contact Information') ?></h2>
                <ul class="form-list">
                    <li class="fields">
                        <div class="field">
                            <label for="name" class="required"><em>*</em><?php echo Mage::helper('supportcontacts')->__('Name') ?></label>
                            <div class="input-box">
                                <input name="name" id="name" title="<?php echo Mage::helper('supportcontacts')->__('Name') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="email" class="required"><em>*</em><?php echo Mage::helper('supportcontacts')->__('Email') ?></label>
                            <div class="input-box">
                                <input name="email" id="email" title="<?php echo Mage::helper('supportcontacts')->__('Email') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                            </div>
                        </div>
                    </li>

                    <li class="fields">
                        <div class="field">
                            <label for="subject"><?php echo Mage::helper('supportcontacts')->__('Subject') ?></label>
                            <div class="input-box">
                                <input name="subject" id="subject" title="<?php echo Mage::helper('supportcontacts')->__('Subject') ?>" value="" class="input-text" type="text" />
                            </div>
                        </div>
                        <div class="field">
                             <label for="telephone"><?php echo Mage::helper('supportcontacts')->__('Telephone') ?></label>
                        <div class="input-box">
                            <input name="telephone" id="telephone" title="<?php echo Mage::helper('supportcontacts')->__('Telephone') ?>" value="" class="input-text" type="text" />
                            </div>
                        </div>

                    </li>
                    <li class="fields">
                        <div class="field">
                            <label for="website url" class="required"><em>*</em><?php echo Mage::helper('supportcontacts')->__('Website url') ?></label>
                            <div class="input-box">
                                <input name="website_url" id="subject" title="<?php echo Mage::helper('supportcontacts')->__('Website url') ?>" value="" class="input-text" type="text" />
                            </div>
                        </div>
                        <div class="field">
                             <label for="magento version" class="required"><em>*</em><?php echo Mage::helper('supportcontacts')->__('Magento version') ?></label>
                             <div class="input-box">
                                <input name="magento_version" id="telephone" title="<?php echo Mage::helper('supportcontacts')->__('Magento version') ?>" value="" class="input-text" type="text" />
                             </div>
                        </div>
                    </li>
                    <li>
                        <div class="field">
                             <label for="magento module" class="required"><em>*</em><?php echo Mage::helper('supportcontacts')->__('Magento module') ?></label>
                             <div class="input-box">
                                <input name="magento_module" id="telephone" title="<?php echo Mage::helper('supportcontacts')->__('Magento module') ?>" value="" class="input-text" type="text" />
                             </div>
                        </div> 
                    </li>
                    <li class="wide">
                        <label for="description" class="required"><em>*</em><?php echo Mage::helper('supportcontacts')->__('Description') ?></label>
                        <div class="input-box">
                            <textarea name="description" id="description" title="<?php echo Mage::helper('supportcontacts')->__('Description') ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                        </div>
                    </li>
                    <li>
                        <label for="attachment"><?php echo Mage::helper('supportcontacts')->__('Attachment') ?></label>
                        <div class="input-box">
                            <input name="MAX_FILE_SIZE" type="hidden" value="2000000" />
                            <input name="attachment" id="attachment" class="input-text" type="file" />
                        </div>
                    </li>
                </ul>
            </div>
            <div class="buttons-set">
                <p class="required"><?php echo Mage::helper('supportcontacts')->__('* Required Fields') ?></p>
                <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
                <button type="submit" title="<?php echo Mage::helper('supportcontacts')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('supportcontacts')->__('Submit') ?></span></span></button>
            </div>
        </form>
</div>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('supportcontacts', true);
//]]>
</script>
