<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="page-title">
    <h1><?php echo Mage::helper('salescontacts')->__('Contact Us') ?></h1>
</div>
<form action="<?php echo $this->getFormAction(); ?>" id="salescontacts" method="post">
    <div class="fieldset">
        <h2 class="legend"><?php echo Mage::helper('salescontacts')->__('Contact Information') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="name" class="required"><em>*</em><?php echo Mage::helper('salescontacts')->__('Name') ?></label>
                    <div class="input-box">
                        <input name="name" id="name" title="<?php echo Mage::helper('salescontacts')->__('Name') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="email" class="required"><em>*</em><?php echo Mage::helper('salescontacts')->__('Email') ?></label>
                    <div class="input-box">
                        <input name="email" id="email" title="<?php echo Mage::helper('salescontacts')->__('Email') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                    </div>
                </div>
            </li>
            
            <li class="fields">
                <div class="field">
                    <label for="subject"><?php echo Mage::helper('salescontacts')->__('Subject') ?></label>
                    <div class="input-box">
                        <input name="subject" id="subject" title="<?php echo Mage::helper('salescontacts')->__('Subject') ?>" value="" class="input-text" type="text" />
                    </div>
                </div>
                <div class="field">
                     <label for="telephone"><?php echo Mage::helper('salescontacts')->__('Telephone') ?></label>
                <div class="input-box">
                    <input name="telephone" id="telephone" title="<?php echo Mage::helper('salescontacts')->__('Telephone') ?>" value="" class="input-text" type="text" />
                    </div>
                </div>
                
            </li>
            <li class="wide">
                <label for="description" class="required"><em>*</em><?php echo Mage::helper('salescontacts')->__('Description') ?></label>
                <div class="input-box">
                    <textarea name="description" id="description" title="<?php echo Mage::helper('salescontacts')->__('Description') ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo Mage::helper('salescontacts')->__('* Required Fields') ?></p>
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <button type="submit" title="<?php echo Mage::helper('salescontacts')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('salescontacts')->__('Submit') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('salescontacts', true);
//]]>
</script>
